### ISSUE TITLE
Handle 10x scaling from >200" files

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#100]
Problem: Illustrator sets the UserUnit property to 10.0 if a page has a dimension greater than 200" and then scales all coordinates accordingly. Currently PDFStitcher (as well as Inkscape, Preview, and other PDF viewers) does not read the UserUnit value.

Possible solutions:
1. Read UserUnit, scale margin/trim accordingly, and define the same userunit in output (relies on consistent UserUnit across pages)
2. Read UserUnit, scale all coordinates accordingly, and define the output UserUnit to 1.0. This will possibly break readability in Adobe Reader (which is limited to 200"), but it will import correctly into Inkscape. It also addresses the page inconsistency issue.
3. Prompt user to choose between these two options?

Note that this probably only happens when processing a projector file already, so there is likely only one or two pages in the input document.

**Comment by mara004** [comment]
I'd rather vote for solution 2. PDFStitcher currently may create over-sized pages anyway, and I think PDF viewers other than the Adobe Reader don't have the 200'' limit.

**Comment by cfcurtis** [comment]
Still an issue, and can exist on smaller pages if the original Adobe Illustrator artboard is larger than 200".

**Comment by cfcurtis** [comment]
Finally closed in PR #190!
