### ISSUE TITLE
Produced PDF has page size of 0 with specific pattern

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#119]
Reported on Facebook at https://www.facebook.com/groups/ProjectorsForSewing/posts/898828591026080

![image](https://user-images.githubusercontent.com/282731/133940194-4caca0ed-d3a0-4251-aebf-03d172ecc36b.png)

I have reached out to pattern designer to see if I can get one page of this pattern for testing.

**Comment by mara004** [comment]
Maybe that PDF defines a UserUnit of 0? I'd like to see the file, too...

**Comment by mara004** [comment]
I first though of a UserUnit 0, but that can't be as the width is correct - really weird.
I'd like to see that file, too...

**Comment by cfcurtis** [comment]
Thanks for the nudge to look at this again, I got a copy of the file from the pattern designer and it turned out that the mediabox was defined as [0, 792, 612, 0] (produced by OpenOffice Draw). I just pushed a fix that should hopefully be good, but feel free to review and make changes!

**Comment by mara004** [comment]
> and it turned out that the mediabox was defined as [0, 792, 612, 0]

As far as I know, the MediaBox format should be `[left_border, bottom_border, right_border, top_border]`
This sounds like an invalid file to me - does it display correctly in Adobe Reader at all?

```python3
if rotation == 90 or rotation == -90:
```
https://github.com/cfcurtis/pdfstitcher/commit/d1b43c1b710eb793c7372d7139c76d9e20ffc4a9#diff-09d0cbaf891d623ac245ccf84485a687b554217349ca55557c60b33234b969aeR135

Why -90 and not 270? I think I checked the spec some time ago that only positive rotation values (90, 180, 270) are allowed.

**Comment by mara004** [comment]
> and it turned out that the mediabox was defined as [0, 792, 612, 0]

```python3
 # The mediabox is typically specified as 
 # [lower left x, lower left y, upper left x, upper left y],
 # but per PDF reference any two opposite corners can be defined
```
Oh, interesting, I didn't know that. On which page/section of the specification is this?

```python3
if rotation == 90 or rotation == -90:
```
https://github.com/cfcurtis/pdfstitcher/commit/d1b43c1b710eb793c7372d7139c76d9e20ffc4a9#diff-09d0cbaf891d623ac245ccf84485a687b554217349ca55557c60b33234b969aeR135

What about rotation of 270°?

**Comment by cfcurtis** [comment]
> Oh, interesting, I didn't know that. On which page/section of the specification is this?
Section 3.8.4: Rectangles of the PDF Reference v1.7.

> What about rotation of 270°? Maybe something like
> 
> ```python
> if (rotation // 90) % 2 != 0:
>     # ...
> ```
> 
> would be safest?

I think this is a great solution, I'll implement it unless you want to :)

**Comment by mara004** [comment]
> I think this is a great solution, I'll implement it unless you want to :)

Nice, feel free to implement it!
