### ISSUE TITLE
Support 4k displays (Windows)

### ISSUE THREAD

**Issue by xsisr** [cfcurtis/pdfstitcher#122]
I have a 4k monitor connected to my laptop on windows. When opening the program on this 4k display, it opens in a very blurry view.
Adding this line into the app in case the OS is windows helps:
`ctypes.windll.shcore.SetProcessDpiAwareness(True)`

**Comment by mara004** [comment]
Do you know if this issue is exclusive to Windows, or are other platforms affected too?

**Comment by xsisr** [comment]
> 
> 
> Do you know if this issue is exclusive to Windows, or are other platforms affected too?

I did not try it on other platforms yet.
Unfortunately i got rid of dualboot on my computer recently (for diskspace and graphics driver reasons). Othewise i would try it on linux too.

**Comment by xsisr** [comment]
@mara004  I can pick this one up btw

**Comment by xsisr** [comment]
@mara004 i have the code ready, but i don't have permissions to push a feature branch and create a pullrequest

**Comment by mara004** [comment]
> i have the code ready, but i don't have permissions to push a feature branch and create a pullrequest

I'm a bit confused - why don't you push your branch to a fork and then create the MR via GitHub?

**Comment by xsisr** [comment]
> > i have the code ready, but i don't have permissions to push a feature branch and create a pullrequest
> 
> I'm sorry I don't fully understand the problem - why don't you push your branch to a fork and then create an MR via GitHub?

Ok, i am used to work in teams and to use bitbucket as a team member mostly. I did not know that i can fork -> push to fork -> pullrequest to original project. Let me try it this way then.

**Comment by mara004** [comment]
Nice - linking #123

**Comment by cfcurtis** [comment]
I think this is resolved, tested on both Windows and Linux and seems to do well. I don't have a 4k mac to test on though.
