### ISSUE TITLE
Page trimmed multiple times

### ISSUE THREAD

**Issue by lucielavickova-tesena** [cfcurtis/pdfstitcher#132]
When using v5.0.2, I am having an issue with page trim - it remembers the previous state of the PDF (maybe it's staying in the app cache?) and trims more and more, instead of applying the current trim settings.
Steps to reproduce:
- I opened a PDF with A4 sewing pattern, set the pages to be joined
- on the second tab, I set trim to value 1,5cm on each side and saved the PDF
![image](https://user-images.githubusercontent.com/83921517/155882469-47ee4e34-5169-4bcb-8d2a-040ac0638bda.png)
- then I realized, the value was too high and I need a lower one - 1,2cm
![image](https://user-images.githubusercontent.com/83921517/155882446-1c8ba0b5-0ba1-4ed5-acf2-5af4961656a5.png)
- therefore, I changed the values to 1,2cm and saved the PDF again (overwriting the output PDF)
![image](https://user-images.githubusercontent.com/83921517/155882584-4b2300d5-d80a-41eb-873c-97eaeb18ee1c.png)
- but it left the previous trim and added 1,2 trim -> my pages were suddenly trimmed by 2,7 cm
![image](https://user-images.githubusercontent.com/83921517/155882575-a254b2cf-1cad-4b55-b0b9-03af08ba1537.png)

In the previous version, 5.0, this is not happening - only the currently set trim is applied.

**Comment by cfcurtis** [comment]
Thanks for bringing this to my attention! I think this and #131 were both caused by a change in how the PDF library operates, but I didn't test it well enough. I'll re-build and make a new release.
