### ISSUE TITLE
Add persistent preferences

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#134]
Currently, PDFStitcher doesn't store any user preferences anywhere. It would be good to add things like:
- User-selectable language
- Units
- Preferred line thickness/colour
- Preferred margins

**Comment by nokeechia** [comment]
@cfcurtis I can see preferences added in 0.7.1, is the issue closed, or is there soemthing else you need?

**Comment by cfcurtis** [comment]
You're right, I'll go ahead and close this, thanks!
