### ISSUE TITLE
Trimbox exception when joining A4 pattern

### ISSUE THREAD

**Issue by lucielavickova-tesena** [cfcurtis/pdfstitcher#135]
When joining a pattern from A4 pages with option to "cut" the excess margins, I get an exception when saving the pdf. 
The error message says an exception was thrown at Trimbox, because of local variable 'new_doc' referenced before assignment.
When I just change the option "cut" to "overlap", I can save the document without any problem. 
It's happening in various patterns.

Version: 0.5.3

<img width="625" alt="pdf stitcher trimbox exception" src="https://user-images.githubusercontent.com/83921517/157091125-842989ef-b6ca-48ef-862c-c660a5fcb60d.png">

Exception:
```
Něco se pokazilo
Výjimka:
/TrimBox
Něco se pokazilo, nebylo možné uložit jako C:\Users\LucieLavickova\OneDrive\Šití\dětské\tepláčky a kalhoty\Kalhoty softshellové Mamas 74-140\pdfstitcher.pdf
local variable 'new_doc' referenced before assignment
Make sure C:\Users\LucieLavickova\OneDrive\Šití\dětské\tepláčky a kalhoty\Kalhoty softshellové Mamas 74-140\pdfstitcher.pdf isn't open in another program
```

**Comment by cfcurtis** [comment]
Does this problem happen for all patterns of a certain designer? I'm thinking maybe the PDF doesn't have a TrimBox defined and my code assumes it does. I will look into it.

**Comment by ahsatan** [comment]
I see this same error also with older Eldenberry Blossoms patterns, e.g. Berry Booties in case you want a specific example.

**Comment by cfcurtis** [comment]
@ahsatan thank you, that helps! I apologize for my delay in getting to this.
