### ISSUE TITLE
Layer options grayed out for files w/ layers after stitching a file w/o layers

### ISSUE THREAD

**Issue by ahsatan** [cfcurtis/pdfstitcher#147]
If I stitch a file like the Gathering Apron from Sew Liberated which has no layers (image file?) then open a new file with layers to edit, the Layers tab shows as grayed out and is non-responsive to clicks.  Restarting the app resumes expected functionality.

Please let me know if you need screenshots or example files!

**Comment by cfcurtis** [comment]
Thanks for the report, I'm guessing I forgot to re-enable tabs when a new document is loaded. Added to the bug list!
