### ISSUE TITLE
Mirror unit selection on second tab

### ISSUE THREAD

**Issue by lucielavickova** [cfcurtis/pdfstitcher#151]
in the version 0.6.1, there is missing the option to select the unit when trimming - cm or inch
in the previous versions, this option was present

![image](https://user-images.githubusercontent.com/16803915/167866647-94a1163d-4bb9-43cc-8c82-6f2c93fb2fe5.png)

**Comment by cfcurtis** [comment]
It was moved to the first tab (options) because of the change in behaviour adding margins to a single page PDF. However, I have thought about mirroring this control on the second tab (like I did with page range) because I realize it's convenient to have there.
