### ISSUE TITLE
Missing czech translations

### ISSUE THREAD

**Issue by lucielavickova** [cfcurtis/pdfstitcher#157]
On the second tab, there is missing czech translation for the field "OR Number of Rows:" - in czech, it should say "**NEBO počet řádků:**"
but in version 0.6.2, there is still the english wording:

![image](https://user-images.githubusercontent.com/16803915/169832250-ccabb1b7-b80e-4b63-8daf-5727e8854faf.png)

also, in the File menu, the options are not translated:
![image](https://user-images.githubusercontent.com/16803915/169832858-bced9236-0906-4c44-9493-a6a77aa64ffb.png)

**Comment by cfcurtis** [comment]
Thanks for the report! The translations do lag a bit behind the English, and when I changed that behaviour I changed the description as well. I have updated it now, but you can also edit translations yourself at https://hosted.weblate.org/translate/pdfstitcher/user-interface/cs/?q=state:%3Ctranslated.
