### ISSUE TITLE
Is Monterey OS 12.5.1 Supported?

### ISSUE THREAD

**Issue by BluegrassTriChick** [cfcurtis/pdfstitcher#161]
Hello!  I just tried to download your program on my mac.  I am running Monterey 12.5.1 OS on a Mac M1.  The error I get: **“pdfstitcher” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.**

Thanks & have a great day!

**Comment by cfcurtis** [comment]
Hello @BluegrassTriChick, I am so sorry for my delayed reply! You've probably figured this out by now, but Apple's security needs to be bypassed to allow for running an app from an unregistered developer. Apple's instructions to do this are at https://support.apple.com/en-ca/guide/mac-help/mh40616/mac.
