### ISSUE TITLE
Error opening encrypted PDFs under macOS 13 on Intel processors

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#195]
Users trying to open encrypted PDFs are greeted with the following:
```
Runtime error: unable to load OpenSSL legacy provider
```
This appears to be limited to some kinds of PDF encryption on Intel macs running macOS 13 (Ventura). I tried to replicate using [this action](https://github.com/cfcurtis/pdfstitcher/actions/workflows/test_openssl.yml) and thought I had it narrowed down to the `MACOSX_DEPLOYMENT_TARGET: "10.9"` (that never worked anyway), but as of August 29 I'm still getting reports of this problem.

**Comment by cfcurtis** [comment]
Replicated [here](https://github.com/cfcurtis/pdfstitcher/actions/runs/5868374229/job/15911100861#step:4:10), but re-running the same workflow ([here](https://github.com/cfcurtis/pdfstitcher/actions/runs/6054195055)) fails to replicate. Must depend on runner selected?

**Comment by cfcurtis** [comment]
Unable to consistently replicate with GitHub action runners, I assume it only affects certain systems. If you have this issue and can help out, please comment on this issue.

**Comment by IvoryTinplate** [comment]
I'm available to help with this, though I am not a programmer! The issue persists on macOS 14, unsurprisingly. I'm running pdfstitcher from the command line in a python 3.9 virtualenv and it works just fine that way. I use other python-based software that has trouble finding the correct openssl install on the newest macOS builds but the fix I use for calibre (delete homebrew's alias `/usr/local/lib/libcrypto.dylib`) doesn't fix pdfstitcher. 

By the way, thank you so much for this project -- I just sent off my first order of large-format prints and was able to assemble some Big4 print-at-home files and include them!

**Comment by cfcurtis** [comment]
@IvoryTinplate thank you so much! It's really useful to know that it works fine from the command line - my suspicion is that it's a problem with building an executable on an older system and then running it on a new one.

I hope to have some time to revisit PDFStitcher in the next month or so, and I may bug you to test it out. Thanks again!

**Comment by sihil** [comment]
Hi @cfcurtis - I came across your blog post when having this issue with a project of mine. 

As a pointer, there is some ongoing conversation about the issue over at https://github.com/pikepdf/pikepdf/issues/520

**Comment by cfcurtis** [comment]
@IvoryTinplate I've packaged a hopefully-fixed version [here](https://github.com/cfcurtis/pdfstitcher/releases/download/v0.9.2/PDFStitcher-InstallerX64.dmg) - if you have some time I'd love it if you could test it out. I'm basically just updating openssl per @sihil's suggestion before bundling with PyInstaller, but I don't have the hardware to check if it solves the issue.
