### ISSUE TITLE
Apple Silicon build yields "unable to load openssl legacy provider" on some PDFs

### ISSUE THREAD

**Issue by clintonblackmore** [cfcurtis/pdfstitcher#205]
### **Summary:**

PDF Stitcher v0.9.2 (Apple Silicon build) fails to open some PDF files, erroring out with the message, "RuntimeError: unable to load openssl legacy provider". The Intel build (also v0.9.2, on the same computer) opens the same files without issue.

I was able to simplify the problem. While the original file I tried was not password protected, opening a password protected file also yields the issue. I created a trivial PDF file in Apple Pages, and exported it with the password `password`. Here it is: [Pages with Password.pdf](https://github.com/cfcurtis/pdfstitcher/files/13788314/Pages.with.Password.pdf). It opens up just fine in Preview, and, as stated, works without issue in the Intel build of PDF Stitcher.

### **Environment:**

I'm using a Mac mini (M2) 2023, running macOS Ventura 13.5.2.

### **Steps To Reproduce**

- Run the Apple Silicon build of PDF stitcher on a suitable computer.
- Select as the "Pages with Password.pdf" file as the input PDF
- Note that you get the following output in the bottom pane:

> Opening /Users/clinton/Documents/Pages with Password.pdf
Traceback (most recent call last):
  File "pdfstitcher/ui/main_frame.py", line 398, in on_open
  File "pdfstitcher/ui/main_frame.py", line 408, in load_file
  File "pikepdf/_methods.py", line 833, in open
RuntimeError: unable to load openssl legacy provider

- Further note that the file did not open.

The expected result is that the file should open without error. 

Interestingly, here is what happens when you use the Intel build.

- Run the Intel build of PDF stitcher on a suitable computer.
- Select as the "Pages with Password.pdf" file as the input PDF
- When prompted for the password, enter `password`
- The file opens.
- The output pane says:

> Opening /Users/clinton/Documents/Pages with Password.pdf
PDF locked! Enter the correct password.
Opening /Users/clinton/Documents/Pages with Password.pdf
PDF file loaded without errors.
Warning: this PDF is encrypted with the following permissions:
accessibility: True
extract: True
modify_annotation: True
modify_assembly: True
modify_form: True
modify_other: True
print_lowres: True
print_highres: True
Please be respectful of the author and only use this tool for personal use.

This is the expected result.

**Comment by cfcurtis** [comment]
Oh no, it's openssl/macOS whack-a-mole! Thanks for letting me know, I'm away for new years but I will take a look when I get back and can access a macOS system.

**Comment by cfcurtis** [comment]
Sorry for the delay, I believe this has been solved with the latest update of pikepdf. I have updated the executable for v0.9.2 (not changing the version number as the code has not actually changed).
