### ISSUE TITLE
Unable to upload files from Wardrobe by Me WBM on my Macbook

### ISSUE THREAD

**Issue by hmeinild** [cfcurtis/pdfstitcher#206]
I have tried several times to upload files from WBM - however it gives me an error:  
PDF file loaded without errors.
Please be respectful of the author and only use this tool for personal use.
Åbner /Users/bruger/Dropbox/PDF symønstre/Wardrobe by me/WBM mens cardigan pattern and instructions/Mens Classic Cardigan A0.pdf
Traceback (most recent call last):
  File "pdfstitcher/ui/main_frame.py", line 398, in on_open
  File "pdfstitcher/ui/main_frame.py", line 408, in load_file
  File "pikepdf/_methods.py", line 833, in open
RuntimeError: unable to load openssl legacy provider

I forwarded the file to a friend that opened it on windows, saved it with a new name and sent it back to me - now I was able to upload it.
However I cannot find the file that I saved on my MAC after working with it on PDF stitcher

**Comment by cfcurtis** [comment]
Hi, thank you for the report! It seems my macos encryption issue has jumped from Intel to Apple processors, sigh. I will hopefully get some time to address this next week, but in the meantime I think you can use the [Intel version](https://github.com/cfcurtis/pdfstitcher/releases/download/v0.9.2/PDFStitcher-InstallerX64.dmg), it just runs a bit slower.

**Comment by cfcurtis** [comment]
I believe this should now be fixed! It's still v0.9.2 as the code has not changed, but the latest version of pikepdf seems to have resolved the openssl issue.
