### ISSUE TITLE
Fehler beim Erstellen eines PDFs

### ISSUE THREAD

**Issue by langer29** [cfcurtis/pdfstitcher#213]
Wird geöffnet: C:\Users\User\OneDrive\Dokumente\Nähen\pattydoo_schnittmuster_amy.pdf
PDF file loaded without errors.
Please be respectful of the author and only use this tool for personal use.
File will be written to C:\Users\User\OneDrive\Dokumente\Nähen\Amy_01.pdf
Zusammensetzten mit 5 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 148.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
File will be written to C:\Users\User\OneDrive\Dokumente\Nähen\Amy_01.pdf
Zusammensetzten mit 5 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 148.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
Zusammensetzten mit 5 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 148.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
Zusammensetzten mit 5 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 148.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
Zusammensetzten mit 2 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 59.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
Zusammensetzten mit 5 Reihen und 6 Spalten
Optionen:
    Ränder: 0.0 cm
    Abschneiden: [0, 0, 0, 0] cm
    Rotation: Keine
    Seiten-Reihenfolge: Reihen dann Spalten, Links nach Rechts, Oben nach Unten
    Vertikale Ausrichtung: Unten
    Horizontale Ausrichtung: Links
Ausgabe-Größe: 125.94 x 148.34 cm
Etwas ist schief gelaufen
Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 200, in on_go_pressed
  File "pdfstitcher\tile_pages.py", line 594, in run
TypeError: only pikepdf.Page can be appended to PageList
```

## Current Configuration
```
general:
  check_updates: true
  language: de_DE
  margin: '0'
  open_dir: "C:\\Users\\User\\OneDrive\\Dokumente\\N\xE4hen"
  save_dir: "C:\\Users\\User\\OneDrive\\Dokumente\\N\xE4hen"
  units: !units 'CENTIMETERS'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: 0.9.2
platform: Windows
platform-release: '10'
platform-version: 10.0.22631
processor: AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 14 GB
```

**Comment by langer29** [comment]
[pattydoo_schnittmuster_amy.pdf](https://github.com/user-attachments/files/15738381/pattydoo_schnittmuster_amy.pdf)

**Comment by cfcurtis** [comment]
Thank you for the report! Coincidentally, I just published a beta version of pdfstitcher 1.0 and can't reproduce this issue. Can you please try https://github.com/cfcurtis/pdfstitcher/releases/download/v1.0b1/pdfstitcher.exe and see if that fixes the problem?

**Comment by cfcurtis** [comment]
Turns out I had accidentally built 0.9.2 again, just a few days after pikepdf released v9.0 with a breaking change for appending to the pagelist. I've updated the 0.9.2 build and made the upcoming 1.0 release compliant with the new pikepdf behaviour. Sorry about this!

**Comment by langer29** [comment]
Hi there,
thanks a lot. 
Seems to work now
