### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lordnynex** [cfcurtis/pdfstitcher#23]
Is there any way to use this software to compose A0 printshop output as opposed to a projection?

**Comment by cfcurtis** [comment]
The output is just a PDF that could theoretically be printed at a printshop. However, it's not constrained in size, so it's up to the pattern designer/user to generate A0 if that's what's needed. I find most adult sized patterns tend to tile larger than A0, but children's sizes could conceivably be printed in large format.
