### ISSUE TITLE
Longer 'Page range' field for more visibility

### ISSUE THREAD

**Issue by Triffen** [cfcurtis/pdfstitcher#26]
Please make the Page Range field longer for those complicated ranges with zeros etc. to be visible.
![LongerPageRangeField_2021-01-24_19-38](https://user-images.githubusercontent.com/4696816/105638615-35699680-5e7c-11eb-8aa7-022d94086dc0.png)

**Comment by cfcurtis** [comment]
Good idea, I'll incorporate this in the next release.
