### ISSUE TITLE
0.4 Pre-Release pdfstitcher fails to launch (Linux)

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#35]
Version 0.4-beta.1 (Pre-Release)
Commit: 1915b50
Platform: KDE Neon based on Ubuntu 20.04 LTS (Linux)
wxPython: distribution-provided package `python3-wxgtk4.0 (4.0.7+dfsg-2build1)`
(wxpython setup from pip3 fails, so I cannot try it with a newer version)

pdfstitcher.py fails to launch:
```
$ python3 pdfstitcher.py 
Traceback (most recent call last):
  File "pdfstitcher.py", line 706, in <module>
    frm = SewGUI(None, title=_('PDF Stitcher') + ' ' + version,size=(w,h))
  File "pdfstitcher.py", line 499, in __init__
    self.lt = LayersTab(nb)
  File "pdfstitcher.py", line 268, in __init__
    self.layer_list.EnableCheckBoxes(True)
AttributeError: 'ListCtrl' object has no attribute 'EnableCheckBoxes'
```

I guess the problem is that pdfstitcher relies on a newer wxpython API than what I have installed, right?

**Comment by cfcurtis** [comment]
Yes, unfortunately the checkbox for the layers list needs wxpython 4.1.0 or higher. I didn't realize that it was quite so new and I rely on it for defining which layers to include in the final output. This is also a good reminder that I need to update my limited documentation!

Is it just wxpython that's not working with pip? I wonder if it's conflicting with your system version somehow, though I'm guessing there are other things that depend on that.

**Comment by mara004** [comment]
> Yes, unfortunately the checkbox for the layers list needs wxpython 4.1.0 or higher. I didn't realize that it was quite so new and I rely on it for defining which layers to include in the final output. This is also a good reminder that I need to update my limited documentation!

Okay, thanks for the explanation.

> Is it just wxpython that's not working with pip? I wonder if it's conflicting with your system version somehow

No, I don't think it's conflicting with the system version. That should be clearly separated into  /usr/lib (distribution python packages), /usr/local/lib (system-wide pip install) and ~.local/lib (local pip install). I also have other packages installed dually without issues.

> though I'm guessing there are other things that depend on that.

Yes, this probably is the problem. wxPython do not build wheels for Linux, because it is too difficult to make them work with all different distributions (https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html). I'll get the necessary library and development packages and then retry. Hopefully the distribution-provided library versions are fine, otherwise it's getting complicated.

**Comment by mara004** [comment]
Okay, it was less complicated than I though. All I had to do was install the `libgtk-3-dev` package, and then pip setup worked (already had the other dependencies because I regularly build software myself). The wheels take rather long to build, however, pushing up cpu usage at 100% all the time.
