### ISSUE TITLE
Interactive Pdf content gets lost with multi-page compositing

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#44]
Example file: `https://www.carnegiehall.org/-/media/CarnegieHall/Files/PDFs/Education/Ensemble-Connect/Ensemble-Connect-brochure.pdf?la=en&hash=6E0730F5F4C1847280DAA84307AC29EB` (tested with Chromium/PDFium and Okular)
All the interactive content (videos, pictures that show overlays on hovering, forms etc.) gets lost after processing the file with PDFStitcher. However, this is low priority since sewing patterns usually don't contain these things, but I'm wondering what the cause could be.

**Comment by cfcurtis** [comment]
Hmm, I haven't tried this out before. It's probably something to do with how the pages are placed as form xobjects (using pikepdf's .as_form_xobject, which maps to QPDF's QPDFPageObjectHelper::getFormXObjectForPage. I'm honestly not sure if Adobe supports interactive content in Form XObjects, but if it does then the fix would probably be upstream in [qpdf](https://github.com/qpdf/qpdf).

**Comment by mara004** [comment]
Maybe I could open an issue at pikepdf and ask about this problem?

**Comment by cfcurtis** [comment]
Sure, that seems like a reasonable place to start. They might refer you up to QPDF but the primary developer for pikepdf is quite knowledgeable about all things PDF and probably will know if it's possible.

**Comment by mara004** [comment]
The pikepdf author said it's indeed a limitation of `qpdf`, though it might be possible to manually transfer interactive content from the `/Root` object.
