### ISSUE TITLE
Don't convert to form xobject if already one page

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#46]
Change how layout works when modifying just one page (e.g. to add margins).

May be related to #37

**Comment by mara004** [comment]
How can one add margins without converting to an xobject?

**Comment by cfcurtis** [comment]
I've actually got a fix for this in the works, just doing some more testing before I push. I'll assign it to myself :)

I basically just modify the coordinate system to reposition the content, modify the stream with page_contents_add, and then put the whole thing on a bigger page.

**Comment by mara004** [comment]
Wow, this sounds interesting.

**Comment by mara004** [comment]
This change somehow introduced new issues. See my reply on the commit.

**Comment by cfcurtis** [comment]
Thanks, I'll look in to it. I should have tested on more operating systems.

**Comment by mara004** [comment]
I don't think it's a matter of the operating system in this case. It more looks like a general bug.
I took a look at the modifications you made, and actually they shouldn't have changed anything for my test case, so I find this quite strange.

**Comment by mara004** [comment]
I think I have found the cause: two missing whitespaces in the `content_txt`. I'll make a PR soon.

**Comment by mara004** [comment]
I have left another note on commit d31bec4, this time concerning the resizing of other boxes.
