### ISSUE TITLE
[Question] Localisation on Linux

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#49]
When I launch PDFStitcher on Linux (from command-line or file manager), the program is always using the English localisation, although my system language is German. Are other Linux users experiencing this behaviour, too, or is it just me? Is there a way to explicitly define the desired locale?

**Comment by cfcurtis** [comment]
I just got my linux install up and running for testing, so I will look in to this. To start, have you compiled the translation files? I only have the text .po files checked in to the repo. You can compile them by installing Babel from pip and running:

`pybabel compile -D pdfstitcher -d locale`

If it is compiled and still not working, you can edit the language in utils.py to be 'de' explicitly and it should load the German locale.

**Comment by mara004** [comment]
Ah, I see - I just forgot to compile the translation, sorry ;).
