### ISSUE TITLE
Translation improvements

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#52]
The German translation contained some problematic semantic mistakes that distorted the actual meaning,
e. g. "Tile Pages" -> "Titelseite" (which is quite wrong)
I also corrected a few spelling mistakes and tried to make the translations sound a little better.
Sorry for not creating a pull request, but I do not know how to rebase properly and shouldn't mix it with the changes I applied to `tile_pages.py`
[pdfstitcher-german-3.zip](https://github.com/cfcurtis/pdfstitcher/files/6360580/pdfstitcher-german-3.zip)

PS: Please also see my file from the latest comment on the closed PR concerning the French translation

**Comment by cfcurtis** [comment]
Hi, thank you for doing this. I don't know any German so I've sent this to the original German translator to look at - she made a video tutorial with the previous version and I don't want to cause confusion by changing things that were in the last release, so I'd prefer to do minimal changes to anything that was in [v0.3](https://github.com/cfcurtis/pdfstitcher/blob/6025c511f98a836b88e9abfe1e495e65bb8136d8/locale/de_DE/LC_MESSAGES/pdfstitcher.po) (minor spelling etc is probably fine).

**Comment by cfcurtis** [comment]
@mara004 I think for now I will use your changes for the new UI elements, but keep the old ones for parts that have been shown in the tutorial. I hope that's okay.

**Comment by mara004** [comment]
Sure, that's fine - it's good you arrange this with the original translator. It would just be nice if we could get rid of those semantic errors at some point. Maybe I should only have changed the confusing mistakes and leave all the other strings untouched, but I somehow couldn't hold off ;)

**Comment by mara004** [comment]
I'll yet try to improve the layers translation a bit; I just noticed I made some faults there.

**Comment by Tataika** [comment]
I just worked on it. So i dont know if you see the chances already. If there is something else, please let me know ;-)

**Comment by mara004** [comment]
@Tataika Cool, thanks. I took a look at your latest commit and added two comments.

**Comment by cfcurtis** [comment]
Thank you both for collaborating on this! I will update the release after work today (I'm guessing I'm about 8 hours behind you).

**Comment by mara004** [comment]
I've just corrected some minor issues with the layers translation:
[pdfstitcher-german-4.zip](https://github.com/cfcurtis/pdfstitcher/files/6366369/pdfstitcher-german-4.zip)

**Comment by mara004** [comment]
And I'd like to mention two code suggestions regarding translations:
- What about making Select/Deselect All a push button rather than a checkbox? I found this a bit puzzling at the first time...
- Do we really need to show the layer name on the Apply/Reset buttons? It''s just that sometimes they are a bit longer and exceed the buttons for the default window size

**Comment by mara004** [comment]
I yet have an update to the French translation (added some missing `accents aigus` and a `{}` placeholder)
I would be glad if those could be checked by a native speaker, altough I verified all changes with a dictionnary.
[pdfstitcher-french-4.zip](https://github.com/cfcurtis/pdfstitcher/files/6366631/pdfstitcher-french-4.zip)

**Comment by cfcurtis** [comment]
> * What about making Select/Deselect All a button rather than a checkbox? I found this a bit puzzling at the first time...

It could be a button for sure. I struggled with this one a bit, it seems there isn't a consistent UI that is commonly used.

> * Do we really need to show the layer name on the Apply/Reset buttons? It''s just that sometimes they are a bit longer and exceed the buttons for the default window size

Originally I just had it as "Apply to selected" but there was confusion where people were expecting it to apply to all the checked layers (which is different in wxListCtrl from the "selected" items). Now there's "Apply to checked" but I don't know the best way of saying to apply just to the highlighted row. Sewing patterns usually have very short layer names, but you're right, they can be long. Maybe a box around the Apply/Reset buttons that operate on just the selected row with the selected layer name outside the buttons?

**Comment by cfcurtis** [comment]
I hope I've merged both of the translations together appropriately - there were a few places where I used a dictionary and chose the one from direct translation, like "Ausblenden" vs "Abschneiden" for trim - Google translate said this was "hide" or "cut off". To me "cut off" is a closer match for trim, so I picked that one, even if the way it is done in the PDF is more like hiding.

I left "Zuschnitts-Einstellungen des Quelldokuments ignorieren" as is, though it's not exactly what's happening either because there is also a "CropBox" inside the PDF. This checkbox also fixed an issue I had with page positioning, even though that doesn't seem to relate to cropping. This is my least favourite control name in English though so I'm happy to have suggetions.

**Comment by mara004** [comment]
Translating software is difficult, and in many cases I'm really not sure.
"Set TrimBox to MediaBox" was one of those. I now think it would be better to just write "TrimBox auf MediaBox einstellen", since it is more precise. My original thought was to describe the setting so that people would get a better idea of what it means, but I think it's not necessary if we have the tooltip.

**Comment by mara004** [comment]
> Originally I just had it as "Apply to selected" but there was confusion where people were expecting it to apply to all the checked layers (which is different in wxListCtrl from the "selected" items). Now there's "Apply to checked" but I don't know the best way of saying to apply just to the highlighted row.

Oh, I see. That can be really confusing. I thought of something like "Apply to current item" or "Apply to highlighted", but I think both is too long.

**Comment by cfcurtis** [comment]
> Translating software is difficult, and in many cases I'm really not sure.
It's surprisingly challenging, I appreciate all your help. I will go back to "TrimBox auf MediaBox einstellen" - it's hard to understand in English also.

**Comment by cfcurtis** [comment]
I updated v0.4.1 rather than creating a new release, so it should be good to go now. Thanks again @mara004 and @Tataika for all your help!

**Comment by mara004** [comment]
Thank you @cfcurtis for developing and maintaining PDFStitcher :)
