### ISSUE TITLE
`bottom_to_top` and `right_to_left` options cause awkward results for mixed-size without scaling

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#58]
(only relevant for `tile_pages_dev`)

These options cause very unexpected results for mixed-size documents when not using scaling.

Right-to-left with scaling:
![with_scaling](https://user-images.githubusercontent.com/65915611/116782372-f2c1e680-aa88-11eb-85dc-b7e8047092c7.png)

Right-to-left without scaling (looks wrong):
![without_scaling](https://user-images.githubusercontent.com/65915611/116782373-f35a7d00-aa88-11eb-98b3-4e8baa3efd90.png)

Left-to-right without scaling:
![without_left_to_right](https://user-images.githubusercontent.com/65915611/116782457-957a6500-aa89-11eb-97b7-39ccb0e597e4.png)

**Comment by cfcurtis** [comment]
I just pushed commit #8b00f02 (not sure how to submit a pull request when I'm the owner of the repository) - it's getting pretty complicated but basically I changed it so it just lays out a grid based on the maximum size of the requested pages. This might not be what you're looking for though, so please let me know.

**Comment by mara004** [comment]
From looking at the code, it seems very good! I currently have too many things to do, but I'll try to test it soon ;)

**Comment by mara004** [comment]
I've tested it now - it's pretty much exactly what I was looking for. Thanks!
