### ISSUE TITLE
Layers turned off, rather than deleted?

### ISSUE THREAD

**Issue by susiej** [cfcurtis/pdfstitcher#60]
Hi,
Instead of going through the pdf structure and removing the bits that aren't in the kept ocgs, they could just be turned off. The current method where you go through the structure means that sometimes some bits are missed, for example on one of my pdfs I have all the notches for every size still there as they must be hidden somewhere else in the structure. This means it's hard to know which notch to mark on my fabric. If you turn them off instead of deleting them, you don't need to hunt down every instance of the ocg. This works for me - approx line 269 of layerfilter.py (obviously you could clean up the on and off lines and remove a whole heap of unnecessary code if you felt like it):  

        OCGs = [oc for oc in output.Root.OCProperties.OCGs if str(oc.Name) in self.keep_ocs]
        Off = [oc for oc in output.Root.OCProperties.OCGs if str(oc.Name) not in self.keep_ocs]
        #output.Root.OCProperties.OCGs = OCGs
        output.Root.OCProperties.D.ON = OCGs
        output.Root.OCProperties.D.OFF = Off

        # by default, unlock all layers and show all OCGs
        output.Root.OCProperties.D.Locked = []
        #output.Root.OCProperties.D.Order = self.filter_ocg_order(output.Root.OCProperties.D.Order)

You don't want to remove the ocgs from the order either as then you wouldn't be able to turn them on and off anymore. If I were writing it, I would have also commented out the locked line, but that's up to you. :)

Susie

**Comment by cfcurtis** [comment]
Thank you for looking in to this! Removing information from the layers is surprisingly tricky and I'm not surprised it sometimes leaves bits behind, and I'm still learning about all the different ways PDFs can be structured.

Most of the time people use the layer selection to isolate one or two sizes and then import into inkscape for more detailed pattern tweaks. The reason why I have the layer selection the way it is is because inkscape does not respect the on/off property of the ocgs, so the content needs to be actually removed, not just hidden.

**Comment by susiej** [comment]
Ahh k. That makes sense :)
Maybe make it an option whether you turn it off or delete them? I'd love to be able to save pdfs with just the correct layers viewable. I can add the option if you want? I'm currently writing a little mac app that is more projector friendly than adobe to view pdfs on my projector. Currently pdfkit (Mac's built in pdf library) doesn't have the ability to turn layers on and off, so I need to be able to save the pdf with the correct layers showing.

**Comment by cfcurtis** [comment]
Sure, that's a great idea! I can't believe how many libraries still don't support OCGs after so many years. It would probably be useful for mobile users as well, and way faster to process than parsing everything.

**Comment by susiej** [comment]
layersfilter.py
34d33
<         self.delete_ocs = True
271,276c270
<         Off = [oc for oc in output.Root.OCProperties.OCGs if str(oc.Name) not in self.keep_ocs]
<         if self.delete_ocs:
<             output.Root.OCProperties.OCGs = OCGs
<         else:
<             output.Root.OCProperties.D.ON = OCGs
<             output.Root.OCProperties.D.OFF = Off
---
>         output.Root.OCProperties.OCGs = OCGs
280,281c274
<         if self.delete_ocs:
<             output.Root.OCProperties.D.Order = self.filter_ocg_order(output.Root.OCProperties.D.Order)
---
>         output.Root.OCProperties.D.Order = self.filter_ocg_order(output.Root.OCProperties.D.Order)


241,244d240
<         self.delete_ocs = wx.CheckBox(layer_pane,label=_('Delete non-selected layers'))
<         self.delete_ocs.SetValue(1)
<         layer_sizer.Add(self.delete_ocs,flag=wx.TOP|wx.LEFT|wx.RIGHT,border=5)
< 
550d545
<             self.layer_filter.delete_ocs = bool(self.lt.delete_ocs.GetValue())

**Comment by susiej** [comment]
wow, diff didn't paste very well :P

**Comment by susiej** [comment]
maybe I should just pull it

**Comment by susiej** [comment]
gah, my fix worked for adobe, but it still shows the extra notches in preview...

**Comment by cfcurtis** [comment]
Oh no! I won't be able to test it out until after work today, but I've noticed that some projector files have a grid layer that's disabled by default. Have you tried one of those to see if the grid shows up?  If not there might be something else in the structure that we could copy.

**Comment by susiej** [comment]
When I used chose the option not to delete the layers, the grid switch on/off correctly for both adobe and preview.
For the delete version (original), if you switched the grid on, it would show up in preview, but not adobe.

**Comment by cfcurtis** [comment]
I merged in your fix and made a small tweak so that layers aren't both hidden and deleted (https://github.com/cfcurtis/pdfstitcher/commit/752b67b2fe165f4ffcd7bb9f1190db4fe9006dac). So far I've only tested on Windows with Adobe reader and the layers hidden in PDFStitcher have weird small eyeball symbols when I show them again, I'm not sure what that's about.

**Comment by mara004** [comment]
> The reason why I have the layer selection the way it is is because inkscape does not respect the on/off property of the ocgs, so the content needs to be actually removed, not just hidden.

Maybe someone should file an issue with Inkscape?

**Comment by cfcurtis** [comment]
There are a number of requests for inkscape to support pdf OCGs, both import and export, but I looked in to it and I think it would require upstream changes to poppler and cairo, so it's not trivial. I decided it was easier for me to just delete the content but in the long term it would be great if inkscape could recognize and write layers.
