### ISSUE TITLE
Page tiling only shows first page with Max & Meena Maxaloons pattern

### ISSUE THREAD

**Issue by cfcurtis** [cfcurtis/pdfstitcher#64]

**Comment by mara004** [comment]
How strange. Was this bug introduced with the `tile_pages_dev` modifications, or did it already exist before?
Does this file contain irregular / problematic content by any chance?

**Comment by cfcurtis** [comment]
I haven't actually looked into this yet, it was a reported issue on the Projectors for Sewing Facebook group so I captured it here, but it's been a busy week. It was before the tile_pages_dev branch was merged in - I still haven't made a new release with that content.

**Comment by cfcurtis** [comment]
Issue was with input file, apparently a corrupt download.
