### ISSUE TITLE
Improve reusability of layerfilter

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#68]
The `LayerFilter` class, more precisely its `run()` method, currently involves dependencies from wxPython, which make it uncomfortable for reuse.
Would it be possible to move the part doing the actual processing to an abstract class that does not depend on wxWidgets, and then have LayerFilter inherit from this class, (re-)implementing the `run()` method with GUI components?

**Comment by cfcurtis** [comment]
This seems like a reasonable plan, I agree that it's not ideal to have wxWidgets dependencies in LayerFilter. I apologize, I haven't been able to spend much time with pdfstitcher lately - hopefully by the end of next week.

**Comment by mara004** [comment]
No problem, take your time, there's no need to hurry ;). I'm quite busy with other things at the moment, too.

**Comment by mara004** [comment]
I've started looking into this a bit, but there is one difficulty:
The abstract class should also have a run() method of course. However, if we do not include wxWidgets dependencies we cannot update the progress bar or check WasCancelled() the way we currently do. Nevertheless, entirely reimplementing the run() method is not an option since it would cause code duplication.
Maybe it's possible to use a generator, i. e. the `yield` statement, but I haven't used that yet so I'm not sure whether it's the right concept here.

**Comment by mara004** [comment]
I've tried to make a draft pull reuqest on this: #71

**Comment by mara004** [comment]
I've just proposed a new pull request: #76

**Comment by mara004** [comment]
Fixed with #77 / 56f628e
