### ISSUE TITLE
[Question] Consider relicensing PageTiler, LayerFilter, PageFilter, pdf_operators and utils under LGPL

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#72]
The processing components of PDFStitcher seem to be very well-reusable in general. They might be interesting for some developers to include in other programs with a different architecture or design pattern, but the rather restrictive GPLv3 license could be a potential blocker, not only for proprietary projects but also for open-source development that tries to keep all dependencies as liberal as possible.
What do you think about the idea of relicensing PageTiler, LayerFilter, PageFilter, pdf_operators, and utils under LGPL? It would still be copyleft, but less strong in that it would allow to import these components in programs with a different (gpl-incompatible) license. Direct modifications would still have to be disclosed, of course.
Maybe, the improved reusability of LGPL processing code could even increase interest in PDFStitcher and help the development process.
@cfcurtis Naturally, this is your program and therefore licensing is solely your descision. I could also understand if you want to stick with GPL, but I wanted to propse it for discussion.
@susiej You have made notable contributions to layerfilter and we won't make any licensing changes without your explicit agreement. Would you be okay with relicensing under LGPL?

**Comment by cfcurtis** [comment]
I'm definitely willing to consider it. I originally chose GPL because I like to encourage open source, but I didn't consider how it could potentially restrict integration with other open source projects with more liberal licenses. I'll do a bit more thorough research on it.

**Comment by cfcurtis** [comment]
After doing some investigation I'm planning to update everything to LGPL when I can get some time on my personal computer. I think it's a good balance of open access and flexibility.

The other thing I want to look into is donations. I've received quite a few donations from the generous members of the sewing community, but now that you two (@mara004 and @susiej) are making significant contributions, I'd like to share. I'll look into some more formal pathways for this, but in the meantime if you could send me an email at c.f.curtis@gmail.com I can paypal you a bit of appreciation.

**Comment by cfcurtis** [comment]
Actually I'm going to undo my change while I figure out the licensing thing... I didn't read closely enough that LGPL is mostly just for libraries, so the language of the header text doesn't really make sense.

**Comment by mara004** [comment]
You're right... If applied to the whole program, the LGPL is not perfect. Maybe MPL would make more sense?

**Comment by cfcurtis** [comment]
MPL sounds good to me, and it's what pikepdf uses to I think it makes sense. @susiej seems to be okay with any decision so I'll go ahead and make that change.

**Comment by mara004** [comment]
Thanks!
