### ISSUE TITLE
tilepages broken

### ISSUE THREAD

**Issue by susiej** [cfcurtis/pdfstitcher#74]
Hi,
I just cloned the new layer branch, but the tiling bit seemed to break my pdf. Was using Eli Monster's Sotnos tshirt as that one has multiple depths for layers. This bug seems to have been introduced between my last pull request and now, in the tile_pages.py. Did that commit get added to the latest release?
Error message in my log is:
Error occurred parsing XMP, replacing with empty XMP.
Warning: The pages {11} have a different size than the page before

I won't look at this issue in this branch. I'll just switch off the checkbox when I'm testing as it's unrelated to the layers issue.
Susie

**Comment by mara004** [comment]
Is it possible that  d31bec4 fixes your issues? The missing whitespace may have broken PageTiler for most cases.

**Comment by susiej** [comment]
I just copied the tile_pages.py from the main branch to the layer branch (just in my local copy) and it fixed it :)

**Comment by cfcurtis** [comment]
Yup, this was my bad, sorry!
