### ISSUE TITLE
LayerFilter.run() requires input document to have the `filepath` attribute

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#86]
While attempting to integrate LayerFilter into my program, I ran into trouble with lines [115](https://github.com/cfcurtis/pdfstitcher/blob/171fbb950a27cfba111d6903a6707b7001fc83cf/layerfilter.py#L115)-[116](https://github.com/cfcurtis/pdfstitcher/blob/171fbb950a27cfba111d6903a6707b7001fc83cf/layerfilter.py#L116):
```
# open a new copy of the input        
output = pikepdf.Pdf.open(self.pdf.filename)
```
`pikepdf.Pdf` objects apparently can't be copied properly, so I see you work around this problem by opening the file a second time. However, my input documents are new (assembled from different source files with versatile pre-processing) and hence do not have the `filename` attribute.
Any ideas what I could do? A more or less simple solution would be to save a temporary file, but this would be somewhat inelegant preformance-wise and I have generally tried to avoid tempfiles so far.

**Comment by mara004** [comment]
It seems like I could just use the input pdf, right?
```
output = self.pdf
```
A side effect (i. e. modifying the input document rather than creating a new one) would be okay for my use-case.

**Comment by cfcurtis** [comment]
I'm honestly not sure if opening a copy is fully necessary, but I wanted to be able to refer back to the original if need be, and it's been useful while debugging. I think your solution would probably work, unless there is somewhere I unexpectedly assume there's an unmodified version of the input document floating around.

**Comment by mara004** [comment]
Okay, I see. I ran some tests yesterday and it seemed to work without a copy for what I tried.
