### ISSUE TITLE
Layer names are wrong sometimes

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#89]
Recently I tested layer manipulation with this document: https://www.edcfiresafe.org/wp-content/uploads/2015/12/Using-Layerd-PDFs-with-Sample-Map.pdf
In the PDF viewer, layer names show up correctly:
![layers_okular](https://user-images.githubusercontent.com/65915611/120889501-c22c1a00-c5fd-11eb-9470-3a7c1aa3570c.png)

In PDFStitcher, however, the layer names look wrong:
![layers_pdfstitcher](https://user-images.githubusercontent.com/65915611/120889515-d3752680-c5fd-11eb-9a35-c62854502ef1.png)

So I added a debug print to see the list of ordered layer names:
```
ordered_names ['Title Block', 'ÿþL\x00a\x00y\x00e\x00r\x00s\x00\x00\x00', 'ÿþG\x00r\x00a\x00t\x00i\x00c\x00u\x00l\x00e\x00\x00\x00', 'ÿþO\x00t\x00h\x00e\x00r\x00\x00\x00', 'ÿþL\x00a\x00b\x00e\x00l\x00s\x00\x00\x00', 'Road - Highway', 'Road - Major', 'Road - Minor', 'ÿþS\x00c\x00h\x00o\x00o\x00l\x00\x00\x00', 'River Annotation', 'ÿþF\x00i\x00r\x00e\x00 \x00S\x00t\x00a\x00t\x00i\x00o\x00n\x00\x00\x00', 'ÿþS\x00c\x00h\x00o\x00o\x00l\x00 \x00S\x00i\x00t\x00e\x00\x00\x00', 'ÿþR\x00o\x00a\x00d\x00\x00\x00', 'ÿþT\x00r\x00e\x00a\x00t\x00m\x00e\x00n\x00t\x00 \x00A\x00r\x00e\x00a\x00\x00\x00', 'CL-1 Project', 'ÿþF\x00i\x00r\x00e\x00 \x00D\x00i\x00s\x00t\x00r\x00i\x00c\x00t\x00\x00\x00', 'ÿþC\x00o\x00l\x00o\x00m\x00a\x00 \x00L\x00o\x00t\x00u\x00s\x00 \x00F\x00S\x00C\x00\x00\x00', 'Vegetation and Topography']
```

Is this a special kind of encoding?

**Comment by cfcurtis** [comment]
Very interesting, I will check this out. Looks like a good and freely available test PDF too.

**Comment by cfcurtis** [comment]
Looks like UTF-16 encoding, but I'm not sure how to detect that or tell pikepdf to do anything differently.

**Comment by mara004** [comment]
Maybe ask about this at pikepdf?
Just out of interest, I looked at the [poppler/qt5 ocg](https://github.com/freedesktop/poppler/blob/master/qt5/src/poppler-optcontent.cc) source code. It seems that line 84 is handling unicode-encoded strings:
```
m_name = UnicodeParsedString(group->getName());
```

**Comment by mara004** [comment]
I think this is probably an issue with pikepdf. Should I file a report?

**Comment by cfcurtis** [comment]
Sure, that's probably a better place than here. I'll close the issue with wontfix here because it does seem to be upstream.
