### ISSUE TITLE
[PageTiler] Comply with requested number of rows and columns

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#91]
There is the following code passage in `PageTiler`:
```python
# columns take priority if both are specified
if self.cols > 0:
    rrows = self.rows
    self.rows = math.ceil(n_tiles/self.cols)
    if rrows != self.rows and rrows != 0:
        print(_('Warning: requested {} columns and {} rows, but {} rows are needed with {} pages').format(self.cols,rrows,self.rows,n_tiles))
else:
    self.cols = math.ceil(n_tiles/self.rows)
```
It basically means that we ignore the rows setting if both rows and columns are specified in a way that the given pages could not be put onto one page.
However, wouldn't it be more logical to honour both settings and use multiple pages instead, i. e. continue on a new page if the one before is filled? Probably that's not needed for working with sewing patterns, but I think for other use cases it would make sense.

**Comment by cfcurtis** [comment]
Sometimes people accidentally put in the wrong number, so I had to make a decision which one to respect. I think splitting over multiple pages would change the functionality quite a bit - perhaps it would make more sense to inherit from this class, or make a separate one that calls page tiling for multiple pages?

**Comment by mara004** [comment]
I will consider these possibilities - I didn't think of making a separate class using PageTiler, which sounds like a reasonable idea at first glance.
Though I'm not sure about the topic of inadvertent wrong numbers. We could still print a warning if multiple pages are used, and I guess users will realise the mistake when viewing the document and can simply re-create with the correct settings.
Also, it would still be possible to automatically resolve the other parameter if only one value was given, so that all pages would fit onto one. Then users who want the current behaviour would only need to type in a single number.

**Comment by mara004** [comment]
I think you're right a separate class really makes sense. It's porbably not worth the additional complexity to add this to PageTiler directly.

**Comment by cfcurtis** [comment]
Honestly I think usually most people just do either rows or columns, both is unnecessary and can introduce error. Perhaps it's the interface that should be modified rather than the functionality.
