### ISSUE TITLE
[PageTiler] Prevent creating oversized pages

### ISSUE THREAD

**Issue by mara004** [cfcurtis/pdfstitcher#92]
Downscale the whole page so that it is within the 200in boundaries

**Comment by cfcurtis** [comment]
The 200 inch thing is actually just a limitation in Adobe Reader, I believe - there are other PDF viewers that may be able to load over 200 inches. Downscaling would be a very bad thing for sewing patterns, so I would prefer to keep this as a simple warning.

**Comment by mara004** [comment]
Oh, I see. I should actually have known that, sorry.
